@startuml pyJiraCli_components

top to bottom direction
skinparam Linetype ortho

file "issue key" as key
file "input file" as i_file
file "search string" as filter
file "profile data" as profile_data

package "pyJiraCli" {
  [main]

  [cmd_import] as import
  [cmd_export] as export
  [cmd_profile] as profile
  [cmd_print] as print
  [cmd_search] as search
}

key .down...> export : <<flow>>
key .down...> print : <<flow>>
profile_data .down...> profile : <<flow>>
filter .down...> search : <<flow>>
i_file .down...> import : <<flow>>

database "Jira Server" as jira_server {
  file "Jira issue" as jira_issue
}

database filesystem {
  file "profile data" as profile_data_files
  file "JSON file" as file
}

main .down.> import : <<flow>>
main .down.> export : <<flow>>
main .down.> profile : <<flow>>
main .down.> print : <<flow>>
main .down.> search : <<flow>>

profile ...down.> profile_data_files : <<flow>>\n<<store/delete/update>>
profile .down...> jira_server : <<authenticate>>
export ...down.> file : <<flow>>\n<<create>>
import ....> jira_issue : <<flow>>\n<<create>>

'Notes
note bottom of profile_data_files
  Server URL, user API token,
  and/or user and password
  are stored in a JSON file.
  The server certificate is placed
  in the same folder (optional).
end note

note bottom of file
  The retrieved ticket data is
  stored in a JSON file.
end note

note top of key
  Unique issue key for
  an existing Jira issue.
end note

note top of profile_data
  The server URL, user API token,
  and/or user and password,
  and a server certificate are stored
  in a profile folder.
  The profile is referenced
  by a unique (folder) name.
end note

note top of filter
  A Jira search string
  to find all matching
  Jira issues.
end note

note top of i_file
  JSON file
  with Jira ticket
  information
end note

@enduml
