@startuml pyJiraCli_components
top to bottom direction
skinparam Linetype ortho

file "issue key" as key
file "input file" as i_file
file "search string" as filter
file "profile data" as input_profile

package "pyJiraCli"{
    [main] as main

    [cmd_import] as import
    [cmd_export] as export
    [cmd_profile]  as profile
    [cmd_print]  as print
    [cmd_search] as search
}

key .down...> export        : <<flow>>
key .down...> print         : <<flow>>
input_profile .down...> profile : <<flow>>
filter .down...> search     : <<flow>>
i_file .down...> import     : <<flow>>

database "Jira Server"{
file "jira Issue" as jira_issue
}


database filesystem {
file "login data" as log_data
file "JSON/csv file" as file
}

main .down.> import : <<flow>>
main .down.> export : <<flow>>
main .down.> profile  : <<flow>>
main .down.> print  : <<flow>>
main .down.> search : <<flow>>

profile ...down.> log_data    : <<flow>>\n<<store/delete>>    
export ...down.> file       : <<flow>>\n<<create>>
import ....> jira_issue : <<flow>>\n<<create>>

' notes '
note bottom of log_data
    username and password or 
    API token is stored in an
    encrypted file
end note

note bottom of file
    the ticket data is stored
    in a JSON or csv file
end note

note top of key
    unique issue key for
    an existing jira issue
end note

note top of input_profile
    the server url, a user api token
    and a server certificate are stored
    in a profile folder
    the profile is reference
    by a unique name
end note

note top of filter
    a jira search string 
    to find all fitting
    jira issues
end note

note top of i_file
    JSON or csv file
    with jira ticket
    information
end note

@endumlsss