@startuml pyJiraCli_components
top to bottom direction
skinparam Linetype ortho

file "issue key" as key
file "input file" as i_file
file "search string" as filter
file "login data" as input_login

package "pyJiraCli"{
    [main] as main

    [cmd_import] as import
    [cmd_export] as export
    [cmd_login]  as login
    [cmd_print]  as print
    [cmd_search] as search
}

key .down...> export        : <<flow>>
key .down...> print         : <<flow>>
input_login .down...> login : <<flow>>
filter .down...> search     : <<flow>>
i_file .down...> import     : <<flow>>

database "Jira Server"{
file "jira Issue" as jira_issue
}


database filesystem {
file "login data" as log_data
file "json/csv file" as file
}

main .down.> import : <<flow>>
main .down.> export : <<flow>>
main .down.> login  : <<flow>>
main .down.> print  : <<flow>>
main .down.> search : <<flow>>

login ...down.> log_data    : <<flow>>\n<<store/delete>>    
export ...down.> file       : <<flow>>\n<<create>>
import ....> jira_issue : <<flow>>\n<<create>>

' notes '
note bottom of log_data
    username and password or 
    API token is stored in an
    encrypted file
end note

note bottom of file
    the ticket data is stored
    in a json or csv file
end note

note top of key
    unique issue key for
    an existing jira issue
end note

note top of input_login
    username, password, API token 
    or a server url can be provided
    to the login command, to store
    the information in a file
end note

note top of filter
    a jira search string 
    to find all fitting
    jira issues
end note

note top of i_file
    json or csv file
    with jira ticket
    information
end note

@endumlsss