@startuml pyJiraCLi_useCase
left to right direction

skinparam actorStyle awesome
actor User as user

package Usescases{
usecase UC1 as "set login information"
usecase UC2 as "create tickets from\n json files"
usecase UC3 as "search Tickets with\nstring parameters/filters"
usecase UC4 as "print Ticket details"
usecase UC5 as "create .json file from ticket"
}

user --> UC1 : set_login
user --> UC2 : import
user --> UC3 : search
user --> UC4 : print
user --> UC5 : export

@enduml